Repository WalletConnect/push-server, pull requests merged in 2022-12, with the labels that each got.

#46 feat: Improve Terraform
  .github/workflows/cd.yml
  .github/workflows/ci_terraform.yml
  terraform/backend.tf
  terraform/ecs/main.tf
  terraform/ecs/variables.tf
  terraform/main.tf
  terraform/provider.tf
  terraform/variables.tf
  terraform/vars/dev.tfvars
  terraform/vars/prod.tfvars
  terraform/vars/staging.tfvars
Labels: enhancement

#53 feat: cover registration logic
  Cargo.lock
  Cargo.toml
  src/env.rs
  src/handlers/register_client.rs
  src/lib.rs
  src/stores/client.rs
  terraform/ecs/main.tf
  terraform/main.tf
  tests/context/server.rs
  tests/functional/mod.rs
  tests/functional/registration.rs
Labels: accepted

#35 feat: allow updating device token
  src/error.rs
  src/handlers/register_client.rs
  src/stores/client.rs
  src/stores/tenant.rs
  tests/functional/registration.rs
Labels: accepted

#60 fix: Pipelines
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Cargo.lock
  src/handlers/mod.rs
  src/lib.rs
  src/main.rs
  src/metrics.rs
  src/providers/apns.rs
  src/providers/mod.rs
  src/state.rs
  src/stores/client.rs
  tests/context/server.rs
Labels: bug, enhancement

#62 feat: add validate workflow
  .github/workflows/cd.yml
  .github/workflows/ci_terraform.yml
  .github/workflows/validate.yml
  integration/integration.test.ts
  package.json
Labels: accepted

#70 feat: Migrate to E2EE webhooks
  README.md
  spec/spec.md
Labels: enhancement

#67 feat: add basic dashboard
  README.md
  terraform/monitoring/main.tf
  terraform/monitoring/variables.tf
Labels: accepted

#72 feat: E2EE
  Cargo.lock
  Cargo.toml
  src/blob.rs
  src/error.rs
  src/handlers/push_message.rs
  src/lib.rs
  src/providers/apns.rs
  src/providers/fcm.rs
  tests/integration.rs
  tests/messages.rs
Labels: enhancement

#73 feat: upgrade limits
  terraform/ecs/main.tf
  terraform/monitoring/main.tf
Labels: accepted
