Repository WalletConnect/push-server, pull requests merged in 2022-10, with the labels that each got.

#19 feat: Webhook Validation
  Cargo.lock
  Cargo.toml
  spec/spec.md
  src/error.rs
  src/handlers/delete_client.rs
  src/handlers/mod.rs
  src/handlers/push_message.rs
  src/handlers/register_client.rs
  src/lib.rs
  src/main.rs
  src/middleware/mod.rs
  src/middleware/validate_signature.rs
  src/providers/mod.rs
  src/relay/mod.rs
  src/state.rs
Labels: enhancement

#21 feat: Readme Updates
  .github/pull_request_template.md
  LICENSE
  README.md
Labels: enhancement

#24 fix: `database_url` is optional in env
  src/env.rs
  src/main.rs
  tests/env/mod.rs
  tests/providers/fcm.rs
  tests/providers/noop.rs
Labels: enhancement, hacktoberfest-accepted

#26 fix: APNS
  README.md
  src/env.rs
  src/error.rs
  src/providers/apns.rs
  src/providers/mod.rs
  tests/env/mod.rs
Labels: bug

#27 feat: Actions Improvements
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/intake.yml
  .github/workflows/release.yml
Labels: enhancement

#32 fix: Only release on manual trigger
  .github/workflows/release.yml
Labels: enhancement

#30 fix: Provider Bugs
  .env.example
  Cargo.lock
  Cargo.toml
  src/env.rs
  src/error.rs
  src/providers/mod.rs
  src/providers/noop.rs
Labels: bug

#31 feat: APNS in Terraform
  .github/workflows/cd.yml
  .github/workflows/ci_terraform.yml
  terraform/ecs/main.tf
  terraform/ecs/variables.tf
  terraform/main.tf
  terraform/variables.tf
Labels: enhancement

#33 feat: Change URL
  terraform/variables.tf
Labels: enhancement

#36 feat: Logging
  Cargo.lock
  Cargo.toml
  docker-compose.yml
  src/main.rs
  src/middleware/validate_signature.rs
  src/providers/apns.rs
  src/providers/fcm.rs
  src/providers/mod.rs
  src/providers/noop.rs
Labels: enhancement

#37 feat: Better Errors
  spec/spec.md
  src/error.rs
  src/handlers/delete_client.rs
  src/handlers/mod.rs
  src/handlers/push_message.rs
  src/handlers/register_client.rs
  src/middleware/validate_signature.rs
  src/stores/client.rs
  src/stores/mod.rs
  src/stores/notification.rs
Labels: enhancement

#39 fix: APNS Topic
  .env.example
  .github/workflows/cd.yml
  .github/workflows/ci_terraform.yml
  src/env.rs
  src/providers/apns.rs
  src/providers/mod.rs
  terraform/ecs/main.tf
  terraform/ecs/variables.tf
  terraform/main.tf
  terraform/variables.tf
Labels: bug
