Repository WalletConnect/push-server, pull requests merged in 2023-10, with the labels that each got.

#226 chore: deploy to production became optional with choice for the `image_tag`
  .github/workflows/auto_deploy.yml
  .github/workflows/cd.yml
  .github/workflows/release.yml
Labels: area-github, accepted

#222 Updated codeowners with Rust team
  .github/codeowners
Labels: accepted

#235 fix: adding `... FOR UPDATE` to lock the row while client creation
  src/stores/client.rs
Labels: accepted

#239 fix: add advisory locking to the client create
  src/stores/client.rs
Labels: accepted

#240 fix: use `axum-client-ip` to get the real client IP
  Cargo.lock
  Cargo.toml
  src/handlers/push_message.rs
  src/handlers/register_client.rs
  src/handlers/single_tenant_wrappers.rs
  src/lib.rs
Labels: accepted

#241 fix: using relay public key from environment variable
  .env.example
  .env.multi-tenant-example
  .env.single-tenant-example
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/ci_terraform.yml
  src/config.rs
  src/lib.rs
  src/middleware/validate_signature.rs
  src/relay/mod.rs
  src/state.rs
  terraform/ecs/main.tf
  terraform/ecs/variables.tf
  terraform/main.tf
  terraform/variables.tf
  tests/context/mod.rs
  tests/context/server.rs
  tests/context/stores.rs
  tests/unit/mod.rs
  tests/unit/relay.rs
Labels: accepted

#243 fix: spacing fix in the terraform main file
  terraform/main.tf
Labels: accepted

#245 chore: adding logs to apns update
  src/handlers/update_apns.rs
Labels: accepted

#246 fix: fixing apns keys encoding
  .github/workflows/ci.yml
  src/handlers/get_tenant.rs
  src/handlers/update_apns.rs
  src/stores/tenant.rs
  tests/context/mod.rs
  tests/functional/multitenant/apns.rs
Labels: accepted

#253 fix: revert to the base64 encoded p8 key
  src/handlers/update_apns.rs
  src/stores/tenant.rs
Labels: accepted

#231 fix: `notification` variable is encoded as a string, fix alert thresholds
  terraform/monitoring/main.tf
Labels: area-telemetry, accepted

#258 chore: adding `for` and `message` for 5xx alerts
  terraform/monitoring/main.tf
Labels: area-telemetry, accepted

#255 chore: fix tenant ID log
  src/handlers/push_message.rs
Labels: accepted

#257 chore: distinguish bad device token errors
  src/error.rs
  src/handlers/push_message.rs
  src/providers/apns.rs
  src/providers/fcm.rs
Labels: accepted

#259 chore: change no data state for 5xx monitoring
  terraform/monitoring/main.tf
Labels: area-telemetry, accepted

#260 fix: remove `for` from evaluation and adding a threshold line
  terraform/monitoring/main.tf
Labels: area-telemetry, accepted

#263 fix: fixing and enabling ignored tests
  tests/functional/multitenant/apns.rs
  tests/functional/multitenant/fcm.rs
  tests/functional/multitenant/mod.rs
  tests/functional/multitenant/tenancy.rs
Labels: area-tests, accepted

#261 fix: adding jwt verification to the apns and fcm update handler
  src/handlers/update_apns.rs
  src/handlers/update_fcm.rs
  tests/functional/multitenant/apns.rs
Labels: area-auth, accepted
