Repository WalletConnect/push-server, pull requests merged in 2023-06, with the labels that each got.

#131 fix(o11y): received notifications metric broken
  terraform/monitoring/main.tf
Labels: accepted

#143 feat: bump parquet and fix builds
  .dockerignore
  Cargo.lock
  Cargo.toml
  src/analytics/mod.rs
  src/error.rs
Labels: area-infra

#144 feat: use latest otel collector image
  terraform/ecs/main.tf
Labels: accepted

#145 fix(hotfix): build info unknown
  src/lib.rs
Labels: accepted

#151 feat: improve default message
  src/providers/apns.rs
Labels: accepted

#148 fix: return correct error code
  Cargo.lock
  src/error.rs
  src/providers/apns.rs
Labels: service-apns, service-apns-sandbox, area-telemetry, accepted

#153 fix: bucket prefix
  src/analytics/mod.rs
Labels: area-telemetry, accepted
