Repository WalletConnect/push-server, pull requests merged in 2023-02, with the labels that each got.

#94 fix: Correct APNS encoding
  src/handlers/update_apns.rs
Labels: C-bug, S-accepted, S-needs-review, A-clients, P-high

#93 feat: Contributor Guide
  .env.multi-tenant-example
  .env.single-tenant-example
  Contributors.md
  README.md
  docker-compose.multi-tenant.yml
  migrations/1675269994_add-sandbox-to-enum.sql
  src/config.rs
  src/error.rs
  src/handlers/push_message.rs
  src/handlers/update_apns.rs
  src/providers/mod.rs
  tests/messages.rs
Labels: A-documentation, C-enhancement, S-accepted, P-high, E-hard

#97 fix(hotfix): dedupe messages
  src/handlers/push_message.rs
  tests/context/server.rs
  tests/functional/mod.rs
  tests/functional/push.rs
Labels: S-accepted

#103 feat: metrics
  Cargo.lock
  src/handlers/create_tenant.rs
  src/handlers/delete_client.rs
  src/handlers/delete_tenant.rs
  src/handlers/push_message.rs
  src/handlers/register_client.rs
  src/handlers/update_apns.rs
  src/handlers/update_fcm.rs
  src/lib.rs
  src/macros.rs
  src/metrics/mod.rs
Labels: C-enhancement, S-accepted, P-mid, E-medium, A-telemetry

#102 fix: tenant url
  src/handlers/create_tenant.rs
  src/handlers/get_tenant.rs
Labels: C-bug, S-accepted, A-tenants, P-high, E-easy

#104 feat: new dashboard
  terraform/monitoring/main.tf
Labels: C-enhancement, S-accepted, A-infra, P-mid, A-telemetry

#106 fix: apns support
  .github/workflows/validate.yml
  Cargo.lock
  src/error.rs
  src/handlers/create_tenant.rs
  src/handlers/get_tenant.rs
  src/handlers/push_message.rs
  src/handlers/update_apns.rs
  src/handlers/update_fcm.rs
  src/stores/tenant.rs
Labels: C-bug, S-accepted, A-tenants, P-high, E-medium, M-multi, U-apns

#107 fix: APNS Store Logic & Tests
  Cargo.lock
  src/handlers/update_apns.rs
  src/stores/tenant.rs
  tenant_migrations/1676813285_fix-apns-team-tokens.sql
  tests/context/mod.rs
  tests/context/server.rs
  tests/context/stores.rs
  tests/integration.rs
  tests/store/mod.rs
  tests/store/tenant.rs
Labels: C-bug, S-accepted, A-tenants, P-high, E-medium, A-tests, M-multi
