Repository WalletConnect/push-server, pull requests merged in 2023-09, with the labels that each got.

#188 fix: data only messages not showing in background
  Cargo.lock
  src/providers/fcm.rs
Labels: accepted

#190 fix: remove use of PAT
  .github/workflows/release.yml
Labels: accepted

#195 fix: compilation errors with `functional_tests` flag
  tests/functional/singletenant/push.rs
  tests/functional/stores/notification.rs
Labels: area-tests

#207 chore: log client database actions
  src/stores/client.rs
Labels: accepted

#209 chore: revert 196
  src/stores/client.rs
  src/stores/notification.rs
Labels: accepted

#214 fix: adding `id` for the updated release script
  .github/workflows/release.yml
Labels: accepted

#216 fix: don't wipe response_message
  src/handlers/push_message.rs
Labels: accepted

#218 chore: extra assert APNS response is non-error
  src/handlers/push_message.rs
  src/providers/apns.rs
Labels: accepted

#221 chore: fixing output variable name in the `release` step
  .github/workflows/release.yml
Labels: accepted

#219 chore: enabling alarm notifications
  terraform/monitoring/main.tf
Labels: area-telemetry, accepted
